// <auto-generated />
namespace CourseManagmentSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Enrollment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Enrollment));
        
        string IMigrationMetadata.Id
        {
            get { return "202502011713547_Enrollment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
